const OK_CODE = 200;
const CREATED_CODE = 201;
const BAD_REQUEST_CODE = 400;
const NOT_FOUNDS_CODE = 404;
const INTERNAL_SERVER_ERROR_CODE = 500;

export { OK_CODE, CREATED_CODE, BAD_REQUEST_CODE, NOT_FOUNDS_CODE, INTERNAL_SERVER_ERROR_CODE };
